stages:
  setup_forest_mask:
    cmd: python src/data/setup_forest_mask.py
    deps:
      - src/data/setup_forest_mask.py
      - ${forest_mask.src}
      - ${s2_10m.src}
    outs:
      - ${forest_mask.matched}
  clip_gbif:
    cmd: python src/data/clip_gbif.py
    deps:
      - src/data/clip_gbif.py
      - ${gbif.src}
      - ${s2_20m.src}
    outs:
      - ${gbif.clipped}
  mask_gbif:
    cmd: python src/data/mask_gbif.py
    deps:
      - src/data/mask_gbif.py
      - ${forest_mask.matched}
      - ${gbif.clipped}
    outs:
      - ${gbif.masked}
  save_species_ids_points:
    cmd: python src/features/save_gbif_points.py
    deps:
      - src/features/save_gbif_points.py
      - ${gbif.masked}
    outs:
      - ${gbif.species_ids}
      - ${gbif.points}
