stages:
  clip_and_binarize_forest_mask:
    cmd: python src/data/clip_binarize_forest_mask.py
    deps:
      - src/data/clip_binarize_forest_mask.py
      - ${forest_mask.src}
      - ${s2_20m.src}
    outs:
      - ${forest_mask.clipped}
  reproject_forest_mask:
    cmd: python src/data/reproject_forest_mask.py
    deps:
      - src/data/reproject_forest_mask.py
      - ${forest_mask.clipped}
    outs:
      - ${forest_mask.reproj}
  polygonize_forest_mask:
    cmd: python src/data/polygonize_forest_mask.py
    deps:
      - src/data/polygonize_forest_mask.py
      - ${forest_mask.reproj}
    outs:
      - ${forest_mask.final}
  clip_gbif:
    cmd: python src/data/clip_gbif.py
    deps:
      - src/data/clip_gbif.py
      - ${gbif.src}
      - ${s2_20m.src}
    outs:
      - ${gbif.clipped}
