stages:
  download_gbif:
    cmd: >-
      python src/iforest_cit_sci_feats/data/download_gbif.py
      -q ${gbif.query}
      -n ${gbif.query_name}
      -o ${gbif.output}
    outs:
      - ${gbif.output}/${gbif.query_name}.zip
      - ${gbif.output}/${gbif.query_name}.json