gbif:
  src: /mnt/FS_data/geosense_data_registry/raw/gbif/all_tracheophyta_non-cult_2024-01-21/all_tracheophyta_non-cult_2024-01-21.parquet
  clipped: ./data/interim/gbif/gbif_clipped.parquet
  masked: ./data/interim/gbif/gbif_masked.parquet
  species_ids: ./data/interim/gbif/species_ids.parquet
  points: ./data/interim/gbif/points.parquet
  verbose: True
  n_procs: 30

forest_mask:
  src: /mnt/FS_data/geosense_data_registry/raw/masks/forest_type_2018/FTY_2018_010m_eu_03035_v010/DATA/FTY_2018_010m_eu_03035_V1_0.tif
  matched: ./data/interim/forest_mask/FTY_2018_010m_eu_03035_V1_0_clipped_EPSG32632.tif
  verbose: True

s2_10m:
  src: ./data/raw/sentinel-2/fca_grid_empty_raster_R10m.tif

s2_20m:
  src: ./data/raw/sentinel-2/fca_grid_empty_raster_R20m.tif

stats:
  n_species: 100
  chunk_size: 1000
  writer: netcdf
  radii:
    - 50
    - 100
    - 500
    - 1000
    - 2000
  out_dir: data/processed
