gbif:
  src: /mnt/FS_data/geosense_data_registry/raw/gbif/all_tracheophyta_non-cult_2024-01-21/all_tracheophyta_non-cult_2024-01-21.parquet
  clipped: ./data/interim/gbif/gbif_clipped.parquet
  masked: ./data/interim/gbif/gbif_masked.parquet
  species_ids: ./data/interim/gbif/species_ids.parquet
  points: ./data/interim/gbif/points.parquet
  verbose: True
  n_procs: 30

forest_mask:
  src: /mnt/FS_data/geosense_data_registry/raw/masks/forest_type_2018/FTY_2018_010m_eu_03035_v010/DATA/FTY_2018_010m_eu_03035_V1_0.tif
  matched: ./data/interim/forest_mask/FTY_2018_010m_eu_03035_V1_0_clipped_EPSG32632.tif
  verbose: True

s2_10m:
  src: ./data/raw/sentinel-2/fca_grid_empty_raster_R10m.tif

s2_20m:
  src: ./data/raw/sentinel-2/fca_grid_empty_raster_R20m.tif

stats_gpu:

stats:
  n_species: 100
  n_chunks: 1000
  radii:
    - 50
    - 100
    - 500
    - 1000
    - 2000
  out_dir: ./data/processed
  out_20m_50r: ./data/processed/20m_50r_stats.parquet
  out_20m_100r: ./data/processed/20m_100r_stats.parquet
  out_20m_500r: ./data/processed/20m_500r_stats.parquet
  out_20m_1000r: ./data/processed/20m_1000r_stats.parquet
  out_20m_2000r: ./data/processed/20m_2000r_stats.parquet
  out_10m_50r: ./data/processed/10m_50r_stats.parquet
  out_10m_100r: ./data/processed/10m_100r_stats.parquet
  out_10m_500r: ./data/processed/10m_500r_stats.parquet
  out_10m_1000r: ./data/processed/10m_1000r_stats.parquet
  out_10m_2000r: ./data/processed/10m_2000r_stats.parquet
