gbif:
  src: /mnt/FS_data/geosense_data_registry/raw/gbif/all_tracheophyta_non-cult_2024-01-21/all_tracheophyta_non-cult_2024-01-21.parquet

forest_mask:
  src: /mnt/FS_data/geosense_data_registry/raw/masks/forest_type_2018/FTY_2018_010m_eu_03035_v010/DATA/FTY_2018_010m_eu_03035_V1_0.tif
  clipped: ./data/interim/forest_mask/FTY_2018_010m_eu_03035_V1_0_clipped.tif
  reproj: ./data/interim/forest_mask/FTY_2018_010m_eu_03035_V1_0_clipped_EPSG32632.tif
  final: ./data/interim/forest_mask/forest_mask.gpkg
  dst_epsg: 32632
  verbose: True

s2_10m:
  src: ./data/raw/sentinel-2/fca_grid_empty_raster_R10m.tif

s2_20m:
  src: ./data/raw/sentinel-2/fca_grid_empty_raster_R20m.tif
