hydra:
  output_subdir: null

fst_mask:
  idir: >
    ${hydra.runtime.cwd}/data/raw/masks/forest_type_2018/FTY_2018_010m_de_03035_v010/DATA
  odir: >
    ${hydra.runtime.cwd}/data/interim
  fn: "forest_mask.gpkg"
  n_procs: -1
  verbose: True
